apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scarcity
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: "app-image"
    newName: "ghcr.io/scarcity-game/roll:latest"
    newTag: "initial"